name = "NetworkDismantle"
uuid = "0b835a0f-6bc9-4e92-a927-f95a75caf496"
authors = ["afternone <afternone@163.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"

[compat]
julia = "1"